spring.application.name=tasks
server.port=8080

# Für den Health Check
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Konfiguration des Standard-Admins der Task Cards App selbst
app.admin.email=${APP_ADMIN_EMAIL:admin@example.com}
app.admin.password=${APP_ADMIN_PASSWORD:12345678}

# Konfiguration der Datenquelle (JDBC, Datenbanksystem, URL, Datenbank)
spring.datasource.url=jdbc:mariadb://localhost:3306/tasks
# Konfiguration der Anmeldedaten
spring.datasource.username=schueler
spring.datasource.password=Geheim01
# JPA passt SQL-Dialekte entsprechend des Treibers/DBMS an
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Konsolenausgabe der SQL-Befehle
spring.jpa.show-sql=true

# Liquibase
#spring.liquibase.change-log=classpath:db/mariadb/changelog-master.xml
# folgendes zuletzt verwendet
spring.liquibase.change-log=db/mariadb/changelog-master.xml

# Hibernate

# The SQL dialect makes Hibernate generate better SQL for the chosen database
# deprecated: spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
# Mit create wird die Tabellenstruktur mit jedem Start der Application neu erstellt,
# mit update hingegen nur Änderungen in der Klassenstruktur übernommen
# none wird verwendet, wenn die DB-Migration mit anderen Frameworks, wie z.B. Liquibase, erfolgt
spring.jpa.hibernate.ddl-auto=update
#none for liquibase
#update

logging.level.org.hibernate.SQL=DEBUG
loggin.level.org.hibernate.type=TRACE

# shared key (statt private)
#jwt.secret = Lehrer
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
security.jwt.expiration-time=3600000

# OpenApi und Swagger UI
springdoc.api-docs.path=/api/api-docs
springdoc.swagger-ui.path=/api/swagger-ui.html
springdoc.swagger-ui.doc-expansion=none