spring.application.name=tasks
server.port=8080

# Actuator / Health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# Konfiguration des Standard-Admins der Task Cards App
app.admin.email=${APP_ADMIN_EMAIL}
app.admin.password=${APP_ADMIN_PASSWORD}

# Datenquelle
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

# Liquibase
# spring.liquibase.change-log=db/mariadb/changelog-master.xml

# Logging
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type=INFO

# JWT
security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME:3600000}

# OpenAPI / Swagger UI
springdoc.api-docs.path=/api/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.doc-expansion=none