spring.application.name=tasks
server.port=8088

# DATASOURCE
spring.datasource.url=jdbc:mariadb://localhost:3306/tasks
spring.datasource.username=schueler
spring.datasource.password=Geheim01

# Hibernate

# The SQL dialect makes Hibernate generate better SQL for the chosen database
# deprecated: spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect

# Hibernate ddl auto (create, create-drop, valdidate, update)
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.SQL=DEBUG
loggin.level.org.hibernate.type=TRACE